/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package account

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/organizations"

	svcapitypes "github.com/crossplane/provider-aws/apis/organizations/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeAccountInput returns input for read
// operation.
func GenerateDescribeAccountInput(cr *svcapitypes.Account) *svcsdk.DescribeAccountInput {
	res := &svcsdk.DescribeAccountInput{}

	if cr.Status.AtProvider.AccountID != nil {
		res.SetAccountId(*cr.Status.AtProvider.AccountID)
	}

	return res
}

// GenerateAccount returns the current state in the form of *svcapitypes.Account.
func GenerateAccount(resp *svcsdk.DescribeAccountOutput) *svcapitypes.Account {
	cr := &svcapitypes.Account{}

	if resp.Account.Id != nil {
		cr.Status.AtProvider.ID = resp.Account.Id
	}

	return cr
}

// GenerateCreateAccountInput returns a create input.
func GenerateCreateAccountInput(cr *svcapitypes.Account) *svcsdk.CreateAccountInput {
	res := &svcsdk.CreateAccountInput{}

	if cr.Spec.ForProvider.AccountName != nil {
		res.SetAccountName(*cr.Spec.ForProvider.AccountName)
	}
	if cr.Spec.ForProvider.Email != nil {
		res.SetEmail(*cr.Spec.ForProvider.Email)
	}
	if cr.Spec.ForProvider.IAMUserAccessToBilling != nil {
		res.SetIamUserAccessToBilling(*cr.Spec.ForProvider.IAMUserAccessToBilling)
	}
	if cr.Spec.ForProvider.RoleName != nil {
		res.SetRoleName(*cr.Spec.ForProvider.RoleName)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f4 := []*svcsdk.Tag{}
		for _, f4iter := range cr.Spec.ForProvider.Tags {
			f4elem := &svcsdk.Tag{}
			if f4iter.Key != nil {
				f4elem.SetKey(*f4iter.Key)
			}
			if f4iter.Value != nil {
				f4elem.SetValue(*f4iter.Value)
			}
			f4 = append(f4, f4elem)
		}
		res.SetTags(f4)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
