/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package account

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/organizations"
	svcsdk "github.com/aws/aws-sdk-go/service/organizations"
	svcsdkapi "github.com/aws/aws-sdk-go/service/organizations/organizationsiface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/organizations/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an Account resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create Account in AWS"
	errUpdate        = "cannot update Account in AWS"
	errDescribe      = "failed to describe Account"
	errDelete        = "failed to delete Account"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Account)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Account)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribeAccountInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribeAccountWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateAccount(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Account)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateAccountInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateAccountWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.CreateAccountStatus.AccountId != nil {
		cr.Status.AtProvider.AccountID = resp.CreateAccountStatus.AccountId
	}
	if resp.CreateAccountStatus.CompletedTimestamp != nil {
		cr.Status.AtProvider.CompletedTimestamp = &metav1.Time{*resp.CreateAccountStatus.CompletedTimestamp}
	}
	if resp.CreateAccountStatus.FailureReason != nil {
		cr.Status.AtProvider.FailureReason = resp.CreateAccountStatus.FailureReason
	}
	if resp.CreateAccountStatus.GovCloudAccountId != nil {
		cr.Status.AtProvider.GovCloudAccountID = resp.CreateAccountStatus.GovCloudAccountId
	}
	if resp.CreateAccountStatus.Id != nil {
		cr.Status.AtProvider.ID = resp.CreateAccountStatus.Id
	}
	if resp.CreateAccountStatus.RequestedTimestamp != nil {
		cr.Status.AtProvider.RequestedTimestamp = &metav1.Time{*resp.CreateAccountStatus.RequestedTimestamp}
	}
	if resp.CreateAccountStatus.State != nil {
		cr.Status.AtProvider.State = resp.CreateAccountStatus.State
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	return e.update(ctx, mg)

}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Account)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	return e.delete(ctx, mg)

}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.OrganizationsAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		delete:         nopDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.OrganizationsAPI
	preObserve     func(context.Context, *svcapitypes.Account, *svcsdk.DescribeAccountInput) error
	postObserve    func(context.Context, *svcapitypes.Account, *svcsdk.DescribeAccountOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.AccountParameters, *svcsdk.DescribeAccountOutput) error
	isUpToDate     func(*svcapitypes.Account, *svcsdk.DescribeAccountOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.Account, *svcsdk.CreateAccountInput) error
	postCreate     func(context.Context, *svcapitypes.Account, *svcsdk.CreateAccountOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	delete         func(context.Context, cpresource.Managed) error
	update         func(context.Context, cpresource.Managed) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.Account, *svcsdk.DescribeAccountInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.Account, _ *svcsdk.DescribeAccountOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.AccountParameters, *svcsdk.DescribeAccountOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.Account, *svcsdk.DescribeAccountOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.Account, *svcsdk.CreateAccountInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Account, _ *svcsdk.CreateAccountOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopDelete(context.Context, cpresource.Managed) error {
	return nil
}
func nopUpdate(context.Context, cpresource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
