/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package organization

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/organizations"

	svcapitypes "github.com/crossplane/provider-aws/apis/organizations/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeOrganizationInput returns input for read
// operation.
func GenerateDescribeOrganizationInput(cr *svcapitypes.Organization) *svcsdk.DescribeOrganizationInput {
	res := &svcsdk.DescribeOrganizationInput{}

	return res
}

// GenerateOrganization returns the current state in the form of *svcapitypes.Organization.
func GenerateOrganization(resp *svcsdk.DescribeOrganizationOutput) *svcapitypes.Organization {
	cr := &svcapitypes.Organization{}

	if resp.Organization.Arn != nil {
		cr.Status.AtProvider.ARN = resp.Organization.Arn
	}
	if resp.Organization.AvailablePolicyTypes != nil {
		f1 := []*svcapitypes.PolicyTypeSummary{}
		for _, f1iter := range resp.Organization.AvailablePolicyTypes {
			f1elem := &svcapitypes.PolicyTypeSummary{}
			if f1iter.Status != nil {
				f1elem.Status = f1iter.Status
			}
			if f1iter.Type != nil {
				f1elem.Type = f1iter.Type
			}
			f1 = append(f1, f1elem)
		}
		cr.Status.AtProvider.AvailablePolicyTypes = f1
	}
	if resp.Organization.Id != nil {
		cr.Status.AtProvider.ID = resp.Organization.Id
	}
	if resp.Organization.MasterAccountArn != nil {
		cr.Status.AtProvider.MasterAccountARN = resp.Organization.MasterAccountArn
	}
	if resp.Organization.MasterAccountEmail != nil {
		cr.Status.AtProvider.MasterAccountEmail = resp.Organization.MasterAccountEmail
	}
	if resp.Organization.MasterAccountId != nil {
		cr.Status.AtProvider.MasterAccountID = resp.Organization.MasterAccountId
	}

	return cr
}

// GenerateCreateOrganizationInput returns a create input.
func GenerateCreateOrganizationInput(cr *svcapitypes.Organization) *svcsdk.CreateOrganizationInput {
	res := &svcsdk.CreateOrganizationInput{}

	if cr.Spec.ForProvider.FeatureSet != nil {
		res.SetFeatureSet(*cr.Spec.ForProvider.FeatureSet)
	}

	return res
}

// GenerateDeleteOrganizationInput returns a deletion input.
func GenerateDeleteOrganizationInput(cr *svcapitypes.Organization) *svcsdk.DeleteOrganizationInput {
	res := &svcsdk.DeleteOrganizationInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
