/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package policy

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/organizations"

	svcapitypes "github.com/crossplane/provider-aws/apis/organizations/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribePolicyInput returns input for read
// operation.
func GenerateDescribePolicyInput(cr *svcapitypes.Policy) *svcsdk.DescribePolicyInput {
	res := &svcsdk.DescribePolicyInput{}

	return res
}

// GeneratePolicy returns the current state in the form of *svcapitypes.Policy.
func GeneratePolicy(resp *svcsdk.DescribePolicyOutput) *svcapitypes.Policy {
	cr := &svcapitypes.Policy{}

	if resp.Policy.PolicySummary != nil {
		f1 := &svcapitypes.PolicySummary{}
		if resp.Policy.PolicySummary.Arn != nil {
			f1.ARN = resp.Policy.PolicySummary.Arn
		}
		if resp.Policy.PolicySummary.AwsManaged != nil {
			f1.AWSManaged = resp.Policy.PolicySummary.AwsManaged
		}
		if resp.Policy.PolicySummary.Description != nil {
			f1.Description = resp.Policy.PolicySummary.Description
		}
		if resp.Policy.PolicySummary.Id != nil {
			f1.ID = resp.Policy.PolicySummary.Id
		}
		if resp.Policy.PolicySummary.Name != nil {
			f1.Name = resp.Policy.PolicySummary.Name
		}
		if resp.Policy.PolicySummary.Type != nil {
			f1.Type = resp.Policy.PolicySummary.Type
		}
		cr.Status.AtProvider.PolicySummary = f1
	}

	return cr
}

// GenerateCreatePolicyInput returns a create input.
func GenerateCreatePolicyInput(cr *svcapitypes.Policy) *svcsdk.CreatePolicyInput {
	res := &svcsdk.CreatePolicyInput{}

	if cr.Spec.ForProvider.Content != nil {
		res.SetContent(*cr.Spec.ForProvider.Content)
	}
	if cr.Spec.ForProvider.Description != nil {
		res.SetDescription(*cr.Spec.ForProvider.Description)
	}
	if cr.Spec.ForProvider.Name != nil {
		res.SetName(*cr.Spec.ForProvider.Name)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range cr.Spec.ForProvider.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}
	if cr.Spec.ForProvider.Type != nil {
		res.SetType(*cr.Spec.ForProvider.Type)
	}

	return res
}

// GenerateUpdatePolicyInput returns an update input.
func GenerateUpdatePolicyInput(cr *svcapitypes.Policy) *svcsdk.UpdatePolicyInput {
	res := &svcsdk.UpdatePolicyInput{}

	if cr.Spec.ForProvider.Content != nil {
		res.SetContent(*cr.Spec.ForProvider.Content)
	}
	if cr.Spec.ForProvider.Description != nil {
		res.SetDescription(*cr.Spec.ForProvider.Description)
	}
	if cr.Spec.ForProvider.Name != nil {
		res.SetName(*cr.Spec.ForProvider.Name)
	}

	return res
}

// GenerateDeletePolicyInput returns a deletion input.
func GenerateDeletePolicyInput(cr *svcapitypes.Policy) *svcsdk.DeletePolicyInput {
	res := &svcsdk.DeletePolicyInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
